# fly.toml file generated for nasin-db on 2023-01-16T19:29:16-05:00

app = "nasin-db"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PGDATA="/var/lib/postgresql/data/pgdata"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 5432
  protocol = "tcp"

  [[services.ports]]
    port = 5432

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[mounts]
  source="nasin_data"
  destination="/var/lib/postgresql/data"
